CREATE database RFM_SALES;

USE RFM_SALES;

SELECT * FROM SAMPLE_SALES_DATA;

-- DROP TABLE SAMPLE_SALES_DATA;
SELECT MAX(STR_TO_DATE(ORDERDATE, '%d/%m/%y')) FROM SAMPLE_SALES_DATA; -- 2005-05-31 [LAST BUSINESS DAY]
SELECT MIN(STR_TO_DATE(ORDERDATE, '%d/%m/%y')) FROM SAMPLE_SALES_DATA; -- 2003-01-06

SELECT
	CUSTOMERNAME,
    ROUND(SUM(SALES),0) AS CLV,
    COUNT(DISTINCT ORDERNUMBER) AS FREQUENCY,
    SUM(QUANTITYORDERED) AS TOTAL_QTY_ORDERED,
    MAX(STR_TO_DATE(ORDERDATE, '%d/%m/%y')) AS CUSTOMER_LAST_TRANSACTION_DATE,
    DATEDIFF((SELECT MAX(STR_TO_DATE(ORDERDATE, '%d/%m/%y')) FROM SAMPLE_SALES_DATA), MAX(STR_TO_DATE(ORDERDATE, '%d/%m/%y'))) AS CUSTOMER_RECENCY
FROM SAMPLE_SALES_DATA
GROUP BY CUSTOMERNAME;


-- RFM SEGMENTATION
CREATE VIEW RFM_SEGMENTATION_DATA AS
WITH CLV AS 
(SELECT
	CUSTOMERNAME,
	MAX(STR_TO_DATE(ORDERDATE, '%d/%m/%y')) AS CUSTOMER_LAST_TRANSACTION_DATE,
    DATEDIFF((SELECT MAX(STR_TO_DATE(ORDERDATE, '%d/%m/%y')) FROM SAMPLE_SALES_DATA), MAX(STR_TO_DATE(ORDERDATE, '%d/%m/%y'))) AS RECENCY_VALUE,
    COUNT(DISTINCT ORDERNUMBER) AS FREQUENCY_VALUE,
    SUM(QUANTITYORDERED) AS TOTAL_QTY_ORDERED,
    ROUND(SUM(SALES),0) AS MONETARY_VALUE
FROM SAMPLE_SALES_DATA
GROUP BY CUSTOMERNAME),



RFM_SCORE AS
(SELECT 
	C.*,
    NTILE(5) OVER(ORDER BY RECENCY_VALUE DESC) AS R_SCORE,
    NTILE(5) OVER(ORDER BY FREQUENCY_VALUE ASC) AS F_SCORE,
    NTILE(5) OVER(ORDER BY MONETARY_VALUE ASC) AS M_SCORE
FROM CLV AS C),

RFM_COMBINATION AS
(SELECT
	R.*,
    R_SCORE + F_SCORE + M_SCORE AS TOTAL_RFM_SCORE,
    CONCAT_WS('', R_SCORE, F_SCORE, M_SCORE) AS RFM_COMBINATION
FROM RFM_SCORE AS R)

SELECT
	RC.*,
    CASE
		WHEN RFM_COMBINATION IN (455, 515, 542, 544, 552, 553, 452, 545, 554, 555) THEN "Champions"
        WHEN RFM_COMBINATION IN (344, 345, 353, 354, 355, 443, 451, 342, 351, 352, 441, 442, 444, 445, 453, 454, 541, 543, 515, 551) THEN 'Loyal Customers'
        WHEN RFM_COMBINATION IN (513, 413, 511, 411, 512, 341, 412, 343, 514) THEN 'Potential Loyalists'
        WHEN RFM_COMBINATION IN (414, 415, 214, 211, 212, 213, 241, 251, 312, 314, 311, 313, 315, 243, 245, 252, 253, 255, 242, 244, 254) THEN 'Promising Customers'
        WHEN RFM_COMBINATION IN (141, 142,143,144,151,152,155,145,153,154,215) THEN 'Needs Attention'
        WHEN RFM_COMBINATION IN (113, 111, 112, 114, 115) THEN 'About to Sleep'
        ELSE "Other"
        END AS CUSTOMER_SEGMENT
FROM RFM_COMBINATION RC;




SELECT
	CUSTOMER_SEGMENT,
    SUM(MONETARY_VALUE) AS TOTAL_SPENDING,
    ROUND(AVG(MONETARY_VALUE),0) AS AVERAGE_SPENDING,
    SUM(FREQUENCY_VALUE) AS TOTAL_ORDER,
    SUM(TOTAL_QTY_ORDERED) AS TOTAL_QTY_ORDERED
FROM RFM_SEGMENTATION_DATA
GROUP BY CUSTOMER_SEGMENT;
SELECT * FROM RFM_SEGMENTATION_DATA;




